llvm build with homebrew, compat configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,41 +1,51 @@
 #!/usr/bin/env bash
 
-echo "brew install llvm instead"
-exit 1
-
 set -e
 set -o pipefail
 set -u
 
-LLVM_VERSION=11.0.0
-LLVM_HASH=827debc34e797b65f60fb27de4078ba9a4c23c321f3d3b42f7c6be31a6d94dcd
-LLVM_CONFIG=${LLVM_CONFIG:-llvm-config}
+if ! which brew; then
+  echo "please install brew first"
+  exit 1
+fi
 
-command -v "${LLVM_CONFIG}" >/dev/null 2>&1 || {
-    PREFIX="deps/clang-${LLVM_VERSION}"
-    if [ ! -f "${PREFIX}/bin/llvm-config" ]; then
-        mkdir -p "deps"
-        FILE="deps/clang-${LLVM_VERSION}.tar.xz"
-        if [ ! -f "${FILE}" ]; then
-            URL="https://github.com/llvm/llvm-project/releases/download/llvmorg-${LLVM_VERSION}/clang+llvm-${LLVM_VERSION}-x86_64-apple-darwin.tar.xz"
-            echo "Downloading ${URL}..."
-            curl --retry 3 -# -S -L "${URL}" -o "${FILE}.tmp" && mv "${FILE}.tmp" "${FILE}"
-        fi
-        echo -n "Checking file... "
-        echo "${LLVM_HASH}  ${FILE}" | shasum -a 512256 -c
-        rm -rf "${PREFIX}"
-        mkdir -p "${PREFIX}"
-        echo -n "Unpacking archive... "
-        tar xf "${FILE}" -C "${PREFIX}" --strip-components 1
-        echo "done."
-    fi
-    LLVM_CONFIG="${PREFIX}/bin/llvm-config"
+if ! test -d "$(brew --prefix)/opt/llvm"; then
+  echo "please install llvm via `brew install llvm`"
+fi
+
+LLVM_CONFIG=$(brew --prefix)/opt/llvm/bin/llvm-config
+
+function build_from_source {
+  LLVM_VERSION=11.0.0
+  LLVM_HASH=827debc34e797b65f60fb27de4078ba9a4c23c321f3d3b42f7c6be31a6d94dcd
+  export LLVM_CONFIG=${LLVM_CONFIG:-llvm-config}
+
+  command -v "${LLVM_CONFIG}" >/dev/null 2>&1 || {
+      PREFIX="deps/clang-${LLVM_VERSION}"
+      if [ ! -f "${PREFIX}/bin/llvm-config" ]; then
+          mkdir -p "deps"
+          FILE="deps/clang-${LLVM_VERSION}.tar.xz"
+          if [ ! -f "${FILE}" ]; then
+              URL="https://github.com/llvm/llvm-project/releases/download/llvmorg-${LLVM_VERSION}/clang+llvm-${LLVM_VERSION}-x86_64-apple-darwin.tar.xz"
+              echo "Downloading ${URL}..."
+              curl --retry 3 -# -S -L "${URL}" -o "${FILE}.tmp" && mv "${FILE}.tmp" "${FILE}"
+          fi
+          echo -n "Checking file... "
+          echo "${LLVM_HASH}  ${FILE}" | shasum -a 512256 -c
+          rm -rf "${PREFIX}"
+          mkdir -p "${PREFIX}"
+          echo -n "Unpacking archive... "
+          tar xf "${FILE}" -C "${PREFIX}" --strip-components 1
+          echo "done."
+      fi
+      LLVM_CONFIG="${PREFIX}/bin/llvm-config"
+  }
+
+  PREFIX="$("${LLVM_CONFIG}" --prefix)"
+  case "${PREFIX}" in
+    *\ *) (>&2 echo "Error: Path to LLVM may not contain spaces: '${PREFIX}'"); exit 1 ;;
+  esac
 }
-
-PREFIX="$("${LLVM_CONFIG}" --prefix)"
-case "${PREFIX}" in
-  *\ *) (>&2 echo "Error: Path to LLVM may not contain spaces: '${PREFIX}'"); exit 1 ;;
-esac
 
 echo "// Do not modify this file. Instead, rerun ./configure" > config.xcconfig
 echo "LLVM_LIBDIR=$(${LLVM_CONFIG} --libdir)" >> config.xcconfig
